name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE by @$AUTHOR in #$NUMBER'

categories:
  - title: 'Features'
    labels: [feature, enhancement]
  - title: 'Fixes'
    labels: [bug, fix]
  - title: 'Maintenance'
    labels: [chore, deps, maintenance]

exclude-labels: [skip-release]

version-resolver:
  major:
    labels: [major, 'breaking change']
  minor:
    labels: [minor, feature, enhancement]
  patch:
    labels: [patch, bug, fix]
  default: patch

template: |
  ## What's Changed
  $CHANGES
