version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: eventapp-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
