# ruff.toml
line-length = 100
target-version = "py313"

[lint]
# Core, bug-preventing rules with low false positives
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes (unused imports/vars, etc.)
  "I",   # isort (ruff's import sorter; compatible with isort)
  "UP",  # pyupgrade (modernize syntax)
  "B",   # flake8-bugbear (common gotchas)
]
ignore = [
  "E501",  # long lines (Black handles wrapping; allow long URLs/strings)
]

[lint.per-file-ignores]
"tests/**" = ["B011"]  # e.g., ignore assert-in-async or other picky test warnings

[format]
# Keep in sync with Black
quote-style = "double"
indent-style = "space"
