"""Remove organization column from organizer_profiles

Revision ID: 065e4ff9a522
Revises: 2bc4ea9ce529
Create Date: 2025-09-06 08:07:15.049812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '065e4ff9a522'
down_revision: Union[str, Sequence[str], None] = '2bc4ea9ce529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS public."ix_organizer_profiles_id"')
    op.execute("DROP TABLE IF EXISTS public.organizer_profiles CASCADE")
    op.alter_column('applications', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('applications', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('events', 'organizer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vendor_profiles', 'services',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('vendor_profiles', 'categories',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('vendor_profiles', 'rate_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('vendor_profiles', 'rate_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('vendor_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('vendor_profiles_user_id_fkey'), 'vendor_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'vendor_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendor_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('vendor_profiles_user_id_fkey'), 'vendor_profiles', 'users', ['user_id'], ['id'])
    op.alter_column('vendor_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vendor_profiles', 'rate_max',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('vendor_profiles', 'rate_min',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('vendor_profiles', 'categories',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vendor_profiles', 'services',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('events', 'organizer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('applications', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('applications', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('organizer_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('organization_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preferred_categories', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('organizer_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('organizer_profiles_pkey'))
    )
    op.create_index(op.f('ix_organizer_profiles_id'), 'organizer_profiles', ['id'], unique=False)
    # ### end Alembic commands ###
