name: CI
on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: eventdb
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/eventdb

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip wheel setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install fastapi uvicorn "SQLAlchemy>=2" alembic psycopg2-binary python-dotenv pydantic ruff

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U postgres && break
            sleep 1
          done

      - name: Alembic upgrade
        run: |
          alembic upgrade head

      - name: DB smoke
        run: |
          python - <<'PY'
          from app.db import engine
          from sqlalchemy import text
          with engine.connect() as c:
              c.execute(text("select 1"))
          print("DB OK")
          PY

      - name: Import smoke
        run: |
          python - <<'PY'
          import fastapi, sqlalchemy, alembic, pydantic
          print("Imports OK")
          PY

      - name: Lint quick
        run: |
          ruff check --select F,E --ignore E501 .
