name: CI
on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip wheel setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install fastapi uvicorn "SQLAlchemy>=2" alembic psycopg2-binary python-dotenv pydantic

      - name: Import smoke
        run: |
          python - <<'PY'
          import fastapi, sqlalchemy, alembic, pydantic
          print("Imports OK")
          PY

      - name: Lint (quick)
        run: |
          python -m pip install ruff
          ruff check --select F,E --ignore E501 .
