      - name: Wait for Postgres (python loop)
        run: |
          python - << 'PY'
          import os, time, psycopg2
          url = os.getenv("DATABASE_URL", "postgresql+psycopg2://postgres:postgres@postgres:5432/eventdb")
          pgurl = url.replace("postgresql+psycopg2://", "postgresql://")
          for i in range(60):
              try:
                  conn = psycopg2.connect(pgurl)
                  conn.close()
                  print("Postgres is ready")
                  break
              except Exception as e:
                  print(f"waiting for Postgres... ({i+1}/60): {e}")
                  time.sleep(1)
          else:
              raise SystemExit("Postgres not ready in time")
          PY

      - name: Run migrations (base -> baseline -> head)
        env:
          # Make sure Alembic sees the URL here too
          DATABASE_URL: ${{ env.DATABASE_URL }}
          PYTHONPATH: .
        run: |
          set -eux
          alembic stamp base
          alembic upgrade 0678be8d8c2b
          alembic --raiseerr upgrade head
