name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # --- Render (trigger via API) ---------------------------------------------
  deploy-render:
    if: ${{ secrets.RENDER_API_KEY && secrets.RENDER_SERVICE_ID }}
    runs-on: ubuntu-24.04
    steps:
      - name: Trigger Render deploy
        run: |
          set -euxo pipefail
          curl -fsSL -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}' \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys

  # --- Fly.io ---------------------------------------------------------------
  deploy-fly:
    if: ${{ secrets.FLY_API_TOKEN }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          set -euxo pipefail
          flyctl deploy --remote-only --auto-confirm

  # --- Railway --------------------------------------------------------------
  deploy-railway:
    if: ${{ secrets.RAILWAY_TOKEN && secrets.RAILWAY_PROJECT_ID }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          set -euxo pipefail
          ~/.railway/bin/railway login --token "$RAILWAY_TOKEN"
          ~/.railway/bin/railway up --project ${{ secrets.RAILWAY_PROJECT_ID }} --ci
