name: lint

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install lint tools
        shell: bash
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install ruff black isort

      - name: Ruff
        shell: bash
        run: ruff check .

      - name: Black (check)
        shell: bash
        run: black --check .

      - name: isort (check)
        shell: bash
        run: isort --check-only --diff .
