name: PR Label Check

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize, ready_for_review]

permissions:
  pull-requests: read

jobs:
  require-semver-label:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR has a semver label (major/minor/patch)
        uses: actions/github-script@v7
        with:
          script: |
            const required = new Set(['major', 'minor', 'patch']);
            const labels = (context.payload.pull_request?.labels || []).map(l => l.name);
            const hasRequired = labels.some(l => required.has(l));
            if (!hasRequired) {
              core.setFailed('Please add one of the required labels: major, minor, or patch.');
            } else {
              core.info(Labels on PR: );
            }
